import { format } from "date-fns";
import jsPDF from "jspdf";

interface MeetingForPdf {
  title: string;
  date: string;
  status: string;
  description?: string | null;
  duration_minutes?: number | null;
  participants?: any;
  agenda?: any;
  notes?: string | null;
  ai_summary?: string | null;
  ai_key_points?: any;
  ai_decisions?: any;
  ai_action_items?: any;
}

export function exportMeetingPdf(meeting: MeetingForPdf) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  const addText = (text: string, size: number, bold = false, color: [number, number, number] = [30, 30, 30]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxWidth);
    if (y + lines.length * (size * 0.5) > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, margin, y);
    y += lines.length * (size * 0.45) + 2;
  };

  const addSection = (title: string, items: string[]) => {
    if (items.length === 0) return;
    y += 4;
    addText(title, 12, true, [50, 80, 160]);
    items.forEach((item, i) => {
      addText(`  ${i + 1}. ${item}`, 10);
    });
  };

  // Header
  addText("MeetingAI — Summary Report", 16, true, [50, 80, 160]);
  y += 2;

  // Title
  addText(meeting.title, 14, true);
  addText(`Date: ${format(new Date(meeting.date), "MMMM d, yyyy 'at' h:mm a")}`, 10, false, [100, 100, 100]);
  addText(`Status: ${meeting.status} · Duration: ${meeting.duration_minutes || 30} min`, 10, false, [100, 100, 100]);

  const participants = Array.isArray(meeting.participants) ? meeting.participants : [];
  if (participants.length > 0) {
    addText(`Participants: ${participants.join(", ")}`, 10, false, [100, 100, 100]);
  }

  // Agenda
  const agenda = Array.isArray(meeting.agenda) ? meeting.agenda : [];
  addSection("Agenda", agenda);

  // Notes
  if (meeting.notes) {
    y += 4;
    addText("Meeting Notes", 12, true, [50, 80, 160]);
    addText(meeting.notes, 10);
  }

  // AI Summary
  if (meeting.ai_summary) {
    y += 4;
    addText("Executive Summary", 12, true, [50, 80, 160]);
    addText(meeting.ai_summary, 10);
  }

  // Key Points
  const keyPoints = Array.isArray(meeting.ai_key_points) ? meeting.ai_key_points : [];
  addSection("Key Points", keyPoints);

  // Decisions
  const decisions = Array.isArray(meeting.ai_decisions) ? meeting.ai_decisions : [];
  addSection("Decisions", decisions);

  // Action Items
  const actionItems = Array.isArray(meeting.ai_action_items) ? meeting.ai_action_items : [];
  addSection("Action Items", actionItems);

  // Footer
  y += 8;
  addText(`Generated by MeetingAI on ${format(new Date(), "MMMM d, yyyy")}`, 8, false, [160, 160, 160]);

  doc.save(`${meeting.title.replace(/[^a-zA-Z0-9]/g, "_")}_summary.pdf`);
}
